### ISSUE TITLE
Requirements Document for Turning on the Lights

### ISSUE THREAD

**Issue by angiedear** [oceanbuilders/ob-web-server#122]
Aside from turning on lights from a switch, what are the other requirements with the lights?

**Comment by angiedear** [comment]
I wrote up the requirements doc, you can find it here: https://docs.google.com/document/d/1HDUE187lcpBaSFrZQoMmmkepjqKvxHwU6dKr5tkKRcU/edit?usp=sharing
It's currently being reviewed by Grant, but if you have any questions or comments, feel free to do so.

**Comment by dramm33** [comment]
One thing that is not on that document (maybe Grant will add or he forgot) is that there are still deciding on the color temperature of the white.

I suggested using cool white (around 6500 K) on the kitchen and bathroom and warm white (around 3000 K) on the rest of the pod. That wouldn't require any extra setting on the app.

So only an RGB selector (outputting 1 byte for each of the three channels) and a separate white slider (also one byte). If we use only the RGB selector, then there must be a separate logic for transforming #FFFFFF (all channels on max, meaning white) to #000000 and 0xFF no the white channel because those are separate in the LEDs we will use.

(Having one white LED on uses less power than three LEDs on. Also, mixing RGB doesn't really produce a good white).

However, it seems Grant wants the option to change the white color in the app. That means 3 bytes for RGB and 2 bytes for the whites (one for cool and the other for warm). I'm now sure how we would be able to integrate that into a color selector and also make it user-friendly. It might make more sense to have the RGB just for the colors and separate sliders for dimming the white and also changing temperature. I didn't test, but I think we can mix the two to make any temperature in between.

**Comment by angiedear** [comment]
That's really good information, I'll bring it up and see what i can get
figured out.  Thank you!

**Comment by scottdear** [comment]
This issue got closed. @dramm33 but you bring up a good point.  I've asked @angiedear to add color changing to the requirements document.  Let's chat about this as I think your issues are addressed in the API that's in the new issues I opened in the smartpod repo.  I'd like to get your input and see if you'd like to get started on some of that.
