### ISSUE TITLE
Raspberry Pi Server - Initial IoT integration

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-web-server#89]

**Comment by Mikisson** [comment]
**Ola Galal** _September 4, 2020, 8:31 AM_

5. Solve problem of access request from outside the network
and put some requests in Postman
Next:

- ask about database structure
- work on MQTT server

**Comment by Mikisson** [comment]
**Ola Galal** _September 4, 2020, 4:35 PM_

6. Make the Server run in background all the time

**Comment by Mikisson** [comment]
**Ola Galal** _September 6, 2020, 11:18 AM_

7. Add auth token and Add SSL certificate to nodejs server

**Comment by Mikisson** [comment]
**Ola Galal** _September 17, 2020, 11:49 AM_

8. Push repo to github, add readme.md and license.md

**Comment by Mikisson** [comment]
**Ola Galal** _September 18, 2020, 8:56 AM_

9. I can now publish to ‘byron/gauge’ topic using nodejs and also subscribe to the same topic and receive messages.

**Comment by olagalal** [comment]
10. Deployed the server on Steve’s Server, it's working in background all time, installed SSL certificate, and connected to MySQL successfully.
I created a dumb test db and table, you can see the endpoints at Postman under (Raspberry Pi Folder)

**Comment by olagalal** [comment]
11. Fetched the list of topics, created an endpoint for it.

**Comment by diegopau** [comment]
@olagalal next steps I would like to see:

a. The app should be able to fetch, for a specific topic, a specific period of data. So please agree with @godslave05 what the API endpoint specification for that should look like. I expect the request to contain two timestamps and the topic, and the response an array of data points. This is assuming that Steve is populating data from the sensor in the database.

b. Then I would like to start testing the other direction of communication: the app will have a page with buttons for different actions that can be triggered. For this we will ask tomorrow to Steve what actuators (devices that you can control from app) he has now available for testing. You will need to provide and endpoint that allows the app to trigger an action and receive acknowledgement.
This should work in this way I think, but we will confirm tomorrow with Steve and you can document here if there are any changes
- Every device that is an actuator will be subscribed to one or more topics, waiting for orders (could be more than 1 topic because maybe the device is something complex, like an AC, that can take many different kind of actions like changing temperature, switching to silent mode, changing direction of the airflow, etc).
- Assuming that Steve's database has always an up-to-date database of available topics, it would be good to expand that table indicating which ones are topics created by sensors and which ones are actuators. This way it will be clear for your server and the app which topics will be populated with real time data from sensors and which topics are only for sending actions that are triggered from the app.
- When the user triggers an action from the app, for example "turn on the light", the server has to publish the order to the topic that controls that device. We definitely need to discuss with Steve how will our server know exactly to which topic to publish if we will have many actuators.
- The server should subscribe to exactly the same topic that is publishing too, because on that topic there should be an acknowledgement (from the hardware it self, the Arduino board will confirm that the light has indeed turned on) that allow our server to send the API response acknowledging that it is all working
